app:
  name: "alianza-interview-backend"
  description: ${app.name} is a Spring Boot application
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_PORT:localhost}:5432/${DB_NAME:alianza-interview}
    username: ${DB_USERNAME:toor}
    password: ${DB_PASSWORD:toor}
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        time_zone: ${TIME_ZONE:UTC}
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    baseline-version: 1
    schemas: "public"
    locations: "classpath:db/migration"
    sql-migration-prefix: "V"
    sql-migration-suffixes: ".sql"
    baseline-on-migrate: ${BASELINE_ON_MIGRATE:true}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVLET_CONTEXT_PATH:}
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
    loggers:
      enabled: true